### ISSUE TITLE
Fatal error - deprecated PHP syntax in font.php on line 83

### ISSUE THREAD

**Issue by SabineSW** [Klap-in/dokuwiki-plugin-emphasis#15]
Hi,

after an upgrade of PHP from 8.0.9 to 8.0.11 dokuwiki (hogfahter) no longer shows proper pages. 

In /var/log/apache2/error.log:
Got error 'PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /data/httpd/wiki/lib/plugins/emphasis/syntax/font.php on line 83'

I saw at least 2 lines (83 and 90) that need fixing: The curly braces {} should be replaced with square brackets [].

Emphasis is not the only plugin affected...

**Comment by Klap-in** [comment]
Thanks for the report, fixed by 0d40f2326af100e062ee9fbb8b1cbe788c79f14e

**Comment by SabineSW** [comment]
Thank you!
